---
title: "Practice shoe"
author: "Eryn Blagg"
date: "10/25/2019"
output: html_document
---


```{r setup}
#library(shoe3d)
library(tidyverse)
library(Morpho)
library(rgl)
library(Rvcg) # package for working with 3d meshes in R
library(MBA) # Spline regression
knitr::opts_chunk$set(cache = T)
```





```{r}
stl_new <- list.files("../data-raw/My_Scans", pattern = ".stl", full.names = T)
stl_file_path1 <- stl_new[str_detect(stl_new, "SonyL")][1]
sony1 <- Rvcg::vcgImport(stl_file_path1, clean = T)
sony1<-Arothron::trasf.mesh(sony1, barycenter = Arothron::bary.mesh(sony1))
stl_file_path2 <- stl_new[str_detect(stl_new, "SonyL")][2]
sony2 <- Rvcg::vcgImport(stl_file_path2, clean = T)
sony2<-Arothron::trasf.mesh(sony2, barycenter = Arothron::bary.mesh(sony2))
```


```{r}
#trying the new shoe_grabber 
Sonyscan<-shoe_grabber(shoeid = "SonyL", scandate = "20190618", filepath = "../data-raw/My_Scans")
```


```{r}
#testing to see if it is doing what i would like for it to do, and it worked for about an hour.... 
rgl::plot3d(sony1, aspect="iso", col="blue", add=TRUE)
rgl::plot3d(sony2, aspect="iso",col="red", add=TRUE)
rgl::plot3d(Sonyscan, aspect="iso", col="green", add=TRUE)
axes3d()
```




Can now use the shoe_grabber function to grab anyshoe given the scan date, which we will be using going forward, since it centers the shoe as well as turning it into a mesh object. 

```{r}
Sonyscan2<-shoe_grabber(shoeid = "SonyL", scandate = "20190618", filepath = "../data-raw/My_Scans")
Sonyscan5<-shoe_grabber(shoeid = "SonyL", scandate = "20191107", filepath = "../data-raw/My_Scans")
```






























```{r}

sony1shoe<-shoe_coord(sony1)

sony2shoe<-shoe_coord(sony2)
```





```{r}
sony1pca<-prcomp(sony1shoe, center = TRUE,scale. = FALSE)
sony2pca<-prcomp(sony2shoe, center = TRUE,scale. = FALSE)
sony1pca$rotation
sony1tran<-transform3d(sony1, matrix = rotationMatrix(matrix = sony1pca$rotation))
sony2tran<-transform3d(sony2, matrix =rotationMatrix(matrix = sony2pca$rotation))
```



```{r}
#Not aligned
rgl::plot3d(sony1tran, aspect="iso", col="blue", add=TRUE)
rgl::plot3d(sony2tran, aspect="iso", col="green", add=TRUE)
axes3d()
```




```{r}
rgl::plot3d(shoeing, aspect="iso", col="green", add=TRUE)
rgl::plot3d(sony1,aspect="iso", col="blue", add=TRUE)
axes3d()
```




```{r}
sony1pca<-prcomp(sony1shoe, center = TRUE,scale. = FALSE)
sony2pca<-prcomp(sony2shoe, center = TRUE,scale. = FALSE)
sony1pca$rotation


```



```{r}
rotattionmat<-rbind(cbind(sony1pca$rotation, c(1, 1, 1)), c(0, 0, 0, 1))
rotattionmat1<-rbind(cbind(t(sony2pca$rotation), c(1, 1, 1)), c(0, 0, 0, 1))
```



```{r}
#FIND A CENTERING??
sony1try<-transform3d(sony1, matrix = rotationMatrix(matrix = rotattionmat))
sony2try<-transform3d(sony2, matrix =rotationMatrix(matrix = rotattionmat1))

#rgl::plot3d(sony1, aspect="iso", col="blue", add=TRUE)
#rgl::plot3d(sony1tran, aspect="iso", col="lightblue", add=TRUE)

#gl::plot3d(sony2, aspect="iso", col="green", add=TRUE)
#rgl::plot3d(sony2tran, aspect="iso", col="lightgreen", add=TRUE)
#axes3d()

rgl::plot3d(sony1try, aspect="iso", col="blue", add=TRUE)
rgl::plot3d(sony2try, aspect="iso", col="green", add=TRUE)
axes3d()

#transform3d(sony1, matrix = rotationMatrix(matrix = sony1pca$rotation))
#par3d(userProjection=rotattionmat)
#rgl::plot3d(sony2, aspect="iso", col="green", add=TRUE)
#par3d(userProjection=rotattionmat1)
```


```{r}
#this is the orginal point clouds 
rgl::plot3d(sony1pca$x, aspect="iso")
rgl::plot3d(sony2pca$x*matrix(c(1, 1, -1), byrow = T, nrow = nrow(sony2pca$x), ncol = 3), aspect="iso", col="blue", add=TRUE)
```









Now with less vertexes: 
```{r}

sony1low<-shoe_coord(sony1, verts = 7)
sony2low<-shoe_coord(sony2, verts = 7)
```

```{r}

```

                                                
```{r}
sony1lowpca<-prcomp(sony1low, center = TRUE,scale. = FALSE)
```



```{r}
sony2lowpca<-prcomp(sony2low, center = TRUE,scale. = FALSE)
```

```{r}
sony1tran<-transform3d(sony1, matrix = rotationMatrix(matrix = diag(c(1,-1,1)) %*% sony1lowpca$rotation))
sony2tran<-transform3d(sony2, matrix = rotationMatrix(matrix = sony2lowpca$rotation))
rgl::plot3d(sony1tran, aspect="iso", col="blue", add=TRUE)
rgl::plot3d(sony2tran, aspect="iso", col="green", add=TRUE)
axes3d()
```









```{r}
rgl::plot3d(sony1lowpca$x, aspect="iso")
rgl::plot3d(sony2lowpca$x*matrix(c(1, 1, -1), byrow = T, nrow = nrow(sony2lowpca$x), ncol = 3), aspect="iso", col="grey", add=TRUE)
```

```{r}
rotattionmata<-rbind(cbind(t(sony1lowpca$rotation), c(0, 0, 0)), c(1, 1, 1, 1))
rotattionmat1a<-rbind(cbind(t(sony2lowpca$rotation), c(0, 0, 0)), c(1, 1, 1, 1))
```

```{r}
rgl::plot3d(sony1low, aspect="iso", col="blue", add=TRUE)
par3d(userProjection=rotattionmata)
rgl::plot3d(sony2low, aspect="iso", col="green", add=TRUE)
par3d(userProjection=rotattionmat1a)
```



Adias 

```{r}
adias <-shoe_grab(shoeid = "002054L",scandate = NULL ,filepath="../data-raw")
```

```{r}
shoe02_1<-adias[[1]][["stl"]][[1]]
shoe02_3<-adias[[1]][["stl"]][[3]]
```


```{r}
Adias1shoe<-shoe_coord(shoe02_1)
Adias3shoe<-shoe_coord(shoe02_3)
```

```{r}
Adias1pca<-prcomp(Adias1shoe, center = TRUE,scale. = FALSE)
```



```{r}
Adias3pca<-prcomp(Adias3shoe, center = TRUE,scale. = FALSE)
```


```{r}
rgl::plot3d(Adias1pca$x, aspect="iso")
rgl::plot3d(Adias3pca$x*matrix(c(1, -1, -1), byrow = T, nrow = nrow(Adias3pca$x), ncol = 3), aspect="iso", col="grey", add=TRUE)
```


```{r}
shoe_flip_angle <- structure(
  c(-0.999475359916687, -0.0319919027388096, -0.0030277690384537, 
     0, -0.0320942476391792, 0.99845552444458, 0.0450587198138237, 
     0, 0.0015826690942049, 0.0451280698180199, -0.998970746994019, 
     0, 0, 0, 0, 1), .Dim = c(4L, 4L)) 

# How to plot:
open3d()
rgl::triangles3d(shoe02_1, aspect = "iso", col = "red")+
view3d(userMatrix = shoe_flip_angle, zoom = .5)

scene <- scene3d()
```






```{r}
#This works really well...it takes a while but now that the shoes are initially centered, this is also centered 
shoeing<-Morpho::pcAlign(sony1,sony2)
```

